// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package com.panda.game.proto;

public final class CmdPb {
  private CmdPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 请求相应接口id
   * </pre>
   *
   * Protobuf enum {@code com.panda.game.proto.Cmd}
   */
  public enum Cmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unkown = 0;</code>
     */
    Unkown(0),
    /**
     * <code>PlayerGetInfoRq = 1001;</code>
     */
    PlayerGetInfoRq(1001),
    /**
     * <code>PlayerGetInfoRs = 1002;</code>
     */
    PlayerGetInfoRs(1002),
    /**
     * <pre>
     * </pre>
     *
     * <code>PlayerSetNameRq = 1003;</code>
     */
    PlayerSetNameRq(1003),
    /**
     * <code>PlayerSetNameRs = 1004;</code>
     */
    PlayerSetNameRs(1004),
    /**
     * <code>FriendGetInfoRq = 2001;</code>
     */
    FriendGetInfoRq(2001),
    /**
     * <code>FriendGetInfoRs = 2002;</code>
     */
    FriendGetInfoRs(2002),
    /**
     * <code>FriendApplyRq = 2003;</code>
     */
    FriendApplyRq(2003),
    /**
     * <code>FriendApplyRs = 2004;</code>
     */
    FriendApplyRs(2004),
    /**
     * <code>ClubGetInfoRq = 3001;</code>
     */
    ClubGetInfoRq(3001),
    /**
     * <code>ClubGetInfoRs = 3002;</code>
     */
    ClubGetInfoRs(3002),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Unkown = 0;</code>
     */
    public static final int Unkown_VALUE = 0;
    /**
     * <code>PlayerGetInfoRq = 1001;</code>
     */
    public static final int PlayerGetInfoRq_VALUE = 1001;
    /**
     * <code>PlayerGetInfoRs = 1002;</code>
     */
    public static final int PlayerGetInfoRs_VALUE = 1002;
    /**
     * <pre>
     * </pre>
     *
     * <code>PlayerSetNameRq = 1003;</code>
     */
    public static final int PlayerSetNameRq_VALUE = 1003;
    /**
     * <code>PlayerSetNameRs = 1004;</code>
     */
    public static final int PlayerSetNameRs_VALUE = 1004;
    /**
     * <code>FriendGetInfoRq = 2001;</code>
     */
    public static final int FriendGetInfoRq_VALUE = 2001;
    /**
     * <code>FriendGetInfoRs = 2002;</code>
     */
    public static final int FriendGetInfoRs_VALUE = 2002;
    /**
     * <code>FriendApplyRq = 2003;</code>
     */
    public static final int FriendApplyRq_VALUE = 2003;
    /**
     * <code>FriendApplyRs = 2004;</code>
     */
    public static final int FriendApplyRs_VALUE = 2004;
    /**
     * <code>ClubGetInfoRq = 3001;</code>
     */
    public static final int ClubGetInfoRq_VALUE = 3001;
    /**
     * <code>ClubGetInfoRs = 3002;</code>
     */
    public static final int ClubGetInfoRs_VALUE = 3002;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Cmd valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Cmd forNumber(int value) {
      switch (value) {
        case 0: return Unkown;
        case 1001: return PlayerGetInfoRq;
        case 1002: return PlayerGetInfoRs;
        case 1003: return PlayerSetNameRq;
        case 1004: return PlayerSetNameRs;
        case 2001: return FriendGetInfoRq;
        case 2002: return FriendGetInfoRs;
        case 2003: return FriendApplyRq;
        case 2004: return FriendApplyRs;
        case 3001: return ClubGetInfoRq;
        case 3002: return ClubGetInfoRs;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Cmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Cmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Cmd>() {
            public Cmd findValueByNumber(int number) {
              return Cmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.panda.game.proto.CmdPb.getDescriptor().getEnumTypes().get(0);
    }

    private static final Cmd[] VALUES = values();

    public static Cmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Cmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.panda.game.proto.Cmd)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcmd.proto\022\024com.panda.game.proto*\345\001\n\003Cm" +
      "d\022\n\n\006Unkown\020\000\022\024\n\017PlayerGetInfoRq\020\351\007\022\024\n\017P" +
      "layerGetInfoRs\020\352\007\022\024\n\017PlayerSetNameRq\020\353\007\022" +
      "\024\n\017PlayerSetNameRs\020\354\007\022\024\n\017FriendGetInfoRq" +
      "\020\321\017\022\024\n\017FriendGetInfoRs\020\322\017\022\022\n\rFriendApply" +
      "Rq\020\323\017\022\022\n\rFriendApplyRs\020\324\017\022\022\n\rClubGetInfo" +
      "Rq\020\271\027\022\022\n\rClubGetInfoRs\020\272\027B\035\n\024com.panda.g" +
      "ame.protoB\005CmdPbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
