// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.panda.game.proto;

public final class CommonPb {
  private CommonPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParamPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.panda.game.proto.ParamPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * <pre>
   * 参数
   * </pre>
   *
   * Protobuf type {@code com.panda.game.proto.ParamPb}
   */
  public static final class ParamPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.panda.game.proto.ParamPb)
      ParamPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParamPb.newBuilder() to construct.
    private ParamPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParamPb() {
      name_ = "";
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ParamPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ParamPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_ParamPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_ParamPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.panda.game.proto.CommonPb.ParamPb.class, com.panda.game.proto.CommonPb.ParamPb.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.panda.game.proto.CommonPb.ParamPb)) {
        return super.equals(obj);
      }
      com.panda.game.proto.CommonPb.ParamPb other = (com.panda.game.proto.CommonPb.ParamPb) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.panda.game.proto.CommonPb.ParamPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.CommonPb.ParamPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.ParamPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.CommonPb.ParamPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.ParamPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.CommonPb.ParamPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.ParamPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.CommonPb.ParamPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.ParamPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.CommonPb.ParamPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.ParamPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.CommonPb.ParamPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.panda.game.proto.CommonPb.ParamPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 参数
     * </pre>
     *
     * Protobuf type {@code com.panda.game.proto.ParamPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.panda.game.proto.ParamPb)
        com.panda.game.proto.CommonPb.ParamPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_ParamPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_ParamPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.panda.game.proto.CommonPb.ParamPb.class, com.panda.game.proto.CommonPb.ParamPb.Builder.class);
      }

      // Construct using com.panda.game.proto.CommonPb.ParamPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_ParamPb_descriptor;
      }

      @java.lang.Override
      public com.panda.game.proto.CommonPb.ParamPb getDefaultInstanceForType() {
        return com.panda.game.proto.CommonPb.ParamPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.panda.game.proto.CommonPb.ParamPb build() {
        com.panda.game.proto.CommonPb.ParamPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.panda.game.proto.CommonPb.ParamPb buildPartial() {
        com.panda.game.proto.CommonPb.ParamPb result = new com.panda.game.proto.CommonPb.ParamPb(this);
        result.name_ = name_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.panda.game.proto.CommonPb.ParamPb) {
          return mergeFrom((com.panda.game.proto.CommonPb.ParamPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.panda.game.proto.CommonPb.ParamPb other) {
        if (other == com.panda.game.proto.CommonPb.ParamPb.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.panda.game.proto.CommonPb.ParamPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.panda.game.proto.CommonPb.ParamPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.panda.game.proto.ParamPb)
    }

    // @@protoc_insertion_point(class_scope:com.panda.game.proto.ParamPb)
    private static final com.panda.game.proto.CommonPb.ParamPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.panda.game.proto.CommonPb.ParamPb();
    }

    public static com.panda.game.proto.CommonPb.ParamPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParamPb>
        PARSER = new com.google.protobuf.AbstractParser<ParamPb>() {
      @java.lang.Override
      public ParamPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParamPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParamPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParamPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.panda.game.proto.CommonPb.ParamPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DropMessagePbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.panda.game.proto.DropMessagePb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 掉落信息
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
     */
    java.util.List<com.panda.game.proto.CommonPb.DropItemMessagePb> 
        getListList();
    /**
     * <pre>
     * 掉落信息
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
     */
    com.panda.game.proto.CommonPb.DropItemMessagePb getList(int index);
    /**
     * <pre>
     * 掉落信息
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
     */
    int getListCount();
    /**
     * <pre>
     * 掉落信息
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
     */
    java.util.List<? extends com.panda.game.proto.CommonPb.DropItemMessagePbOrBuilder> 
        getListOrBuilderList();
    /**
     * <pre>
     * 掉落信息
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
     */
    com.panda.game.proto.CommonPb.DropItemMessagePbOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 掉落信息
   * </pre>
   *
   * Protobuf type {@code com.panda.game.proto.DropMessagePb}
   */
  public static final class DropMessagePb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.panda.game.proto.DropMessagePb)
      DropMessagePbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DropMessagePb.newBuilder() to construct.
    private DropMessagePb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DropMessagePb() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DropMessagePb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DropMessagePb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                list_ = new java.util.ArrayList<com.panda.game.proto.CommonPb.DropItemMessagePb>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(com.panda.game.proto.CommonPb.DropItemMessagePb.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_DropMessagePb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_DropMessagePb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.panda.game.proto.CommonPb.DropMessagePb.class, com.panda.game.proto.CommonPb.DropMessagePb.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<com.panda.game.proto.CommonPb.DropItemMessagePb> list_;
    /**
     * <pre>
     * 掉落信息
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.panda.game.proto.CommonPb.DropItemMessagePb> getListList() {
      return list_;
    }
    /**
     * <pre>
     * 掉落信息
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.panda.game.proto.CommonPb.DropItemMessagePbOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <pre>
     * 掉落信息
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
     */
    @java.lang.Override
    public int getListCount() {
      return list_.size();
    }
    /**
     * <pre>
     * 掉落信息
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
     */
    @java.lang.Override
    public com.panda.game.proto.CommonPb.DropItemMessagePb getList(int index) {
      return list_.get(index);
    }
    /**
     * <pre>
     * 掉落信息
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
     */
    @java.lang.Override
    public com.panda.game.proto.CommonPb.DropItemMessagePbOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.panda.game.proto.CommonPb.DropMessagePb)) {
        return super.equals(obj);
      }
      com.panda.game.proto.CommonPb.DropMessagePb other = (com.panda.game.proto.CommonPb.DropMessagePb) obj;

      if (!getListList()
          .equals(other.getListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.panda.game.proto.CommonPb.DropMessagePb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.CommonPb.DropMessagePb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.DropMessagePb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.CommonPb.DropMessagePb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.DropMessagePb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.CommonPb.DropMessagePb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.DropMessagePb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.CommonPb.DropMessagePb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.DropMessagePb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.CommonPb.DropMessagePb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.DropMessagePb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.CommonPb.DropMessagePb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.panda.game.proto.CommonPb.DropMessagePb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 掉落信息
     * </pre>
     *
     * Protobuf type {@code com.panda.game.proto.DropMessagePb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.panda.game.proto.DropMessagePb)
        com.panda.game.proto.CommonPb.DropMessagePbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_DropMessagePb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_DropMessagePb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.panda.game.proto.CommonPb.DropMessagePb.class, com.panda.game.proto.CommonPb.DropMessagePb.Builder.class);
      }

      // Construct using com.panda.game.proto.CommonPb.DropMessagePb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_DropMessagePb_descriptor;
      }

      @java.lang.Override
      public com.panda.game.proto.CommonPb.DropMessagePb getDefaultInstanceForType() {
        return com.panda.game.proto.CommonPb.DropMessagePb.getDefaultInstance();
      }

      @java.lang.Override
      public com.panda.game.proto.CommonPb.DropMessagePb build() {
        com.panda.game.proto.CommonPb.DropMessagePb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.panda.game.proto.CommonPb.DropMessagePb buildPartial() {
        com.panda.game.proto.CommonPb.DropMessagePb result = new com.panda.game.proto.CommonPb.DropMessagePb(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.panda.game.proto.CommonPb.DropMessagePb) {
          return mergeFrom((com.panda.game.proto.CommonPb.DropMessagePb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.panda.game.proto.CommonPb.DropMessagePb other) {
        if (other == com.panda.game.proto.CommonPb.DropMessagePb.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.panda.game.proto.CommonPb.DropMessagePb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.panda.game.proto.CommonPb.DropMessagePb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.panda.game.proto.CommonPb.DropItemMessagePb> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          list_ = new java.util.ArrayList<com.panda.game.proto.CommonPb.DropItemMessagePb>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.panda.game.proto.CommonPb.DropItemMessagePb, com.panda.game.proto.CommonPb.DropItemMessagePb.Builder, com.panda.game.proto.CommonPb.DropItemMessagePbOrBuilder> listBuilder_;

      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public java.util.List<com.panda.game.proto.CommonPb.DropItemMessagePb> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public com.panda.game.proto.CommonPb.DropItemMessagePb getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public Builder setList(
          int index, com.panda.game.proto.CommonPb.DropItemMessagePb value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public Builder setList(
          int index, com.panda.game.proto.CommonPb.DropItemMessagePb.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public Builder addList(com.panda.game.proto.CommonPb.DropItemMessagePb value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public Builder addList(
          int index, com.panda.game.proto.CommonPb.DropItemMessagePb value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public Builder addList(
          com.panda.game.proto.CommonPb.DropItemMessagePb.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public Builder addList(
          int index, com.panda.game.proto.CommonPb.DropItemMessagePb.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.panda.game.proto.CommonPb.DropItemMessagePb> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public com.panda.game.proto.CommonPb.DropItemMessagePb.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public com.panda.game.proto.CommonPb.DropItemMessagePbOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public java.util.List<? extends com.panda.game.proto.CommonPb.DropItemMessagePbOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public com.panda.game.proto.CommonPb.DropItemMessagePb.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.panda.game.proto.CommonPb.DropItemMessagePb.getDefaultInstance());
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public com.panda.game.proto.CommonPb.DropItemMessagePb.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.panda.game.proto.CommonPb.DropItemMessagePb.getDefaultInstance());
      }
      /**
       * <pre>
       * 掉落信息
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.DropItemMessagePb list = 1;</code>
       */
      public java.util.List<com.panda.game.proto.CommonPb.DropItemMessagePb.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.panda.game.proto.CommonPb.DropItemMessagePb, com.panda.game.proto.CommonPb.DropItemMessagePb.Builder, com.panda.game.proto.CommonPb.DropItemMessagePbOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.panda.game.proto.CommonPb.DropItemMessagePb, com.panda.game.proto.CommonPb.DropItemMessagePb.Builder, com.panda.game.proto.CommonPb.DropItemMessagePbOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.panda.game.proto.DropMessagePb)
    }

    // @@protoc_insertion_point(class_scope:com.panda.game.proto.DropMessagePb)
    private static final com.panda.game.proto.CommonPb.DropMessagePb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.panda.game.proto.CommonPb.DropMessagePb();
    }

    public static com.panda.game.proto.CommonPb.DropMessagePb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DropMessagePb>
        PARSER = new com.google.protobuf.AbstractParser<DropMessagePb>() {
      @java.lang.Override
      public DropMessagePb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DropMessagePb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DropMessagePb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DropMessagePb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.panda.game.proto.CommonPb.DropMessagePb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DropItemMessagePbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.panda.game.proto.DropItemMessagePb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * item表id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     * @return The itemId.
     */
    int getItemId();

    /**
     * <pre>
     * 数量
     * </pre>
     *
     * <code>int64 count = 2;</code>
     * @return The count.
     */
    long getCount();

    /**
     * <pre>
     * 其他参数
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
     */
    java.util.List<com.panda.game.proto.CommonPb.ParamPb> 
        getParamsList();
    /**
     * <pre>
     * 其他参数
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
     */
    com.panda.game.proto.CommonPb.ParamPb getParams(int index);
    /**
     * <pre>
     * 其他参数
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
     */
    int getParamsCount();
    /**
     * <pre>
     * 其他参数
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
     */
    java.util.List<? extends com.panda.game.proto.CommonPb.ParamPbOrBuilder> 
        getParamsOrBuilderList();
    /**
     * <pre>
     * 其他参数
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
     */
    com.panda.game.proto.CommonPb.ParamPbOrBuilder getParamsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 掉落道具信息
   * </pre>
   *
   * Protobuf type {@code com.panda.game.proto.DropItemMessagePb}
   */
  public static final class DropItemMessagePb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.panda.game.proto.DropItemMessagePb)
      DropItemMessagePbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DropItemMessagePb.newBuilder() to construct.
    private DropItemMessagePb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DropItemMessagePb() {
      params_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DropItemMessagePb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DropItemMessagePb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              itemId_ = input.readInt32();
              break;
            }
            case 16: {

              count_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                params_ = new java.util.ArrayList<com.panda.game.proto.CommonPb.ParamPb>();
                mutable_bitField0_ |= 0x00000001;
              }
              params_.add(
                  input.readMessage(com.panda.game.proto.CommonPb.ParamPb.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          params_ = java.util.Collections.unmodifiableList(params_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_DropItemMessagePb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_DropItemMessagePb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.panda.game.proto.CommonPb.DropItemMessagePb.class, com.panda.game.proto.CommonPb.DropItemMessagePb.Builder.class);
    }

    public static final int ITEMID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <pre>
     * item表id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     * @return The itemId.
     */
    @java.lang.Override
    public int getItemId() {
      return itemId_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private long count_;
    /**
     * <pre>
     * 数量
     * </pre>
     *
     * <code>int64 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public long getCount() {
      return count_;
    }

    public static final int PARAMS_FIELD_NUMBER = 3;
    private java.util.List<com.panda.game.proto.CommonPb.ParamPb> params_;
    /**
     * <pre>
     * 其他参数
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.panda.game.proto.CommonPb.ParamPb> getParamsList() {
      return params_;
    }
    /**
     * <pre>
     * 其他参数
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.panda.game.proto.CommonPb.ParamPbOrBuilder> 
        getParamsOrBuilderList() {
      return params_;
    }
    /**
     * <pre>
     * 其他参数
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
     */
    @java.lang.Override
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <pre>
     * 其他参数
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
     */
    @java.lang.Override
    public com.panda.game.proto.CommonPb.ParamPb getParams(int index) {
      return params_.get(index);
    }
    /**
     * <pre>
     * 其他参数
     * </pre>
     *
     * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
     */
    @java.lang.Override
    public com.panda.game.proto.CommonPb.ParamPbOrBuilder getParamsOrBuilder(
        int index) {
      return params_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != 0) {
        output.writeInt32(1, itemId_);
      }
      if (count_ != 0L) {
        output.writeInt64(2, count_);
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeMessage(3, params_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemId_);
      }
      if (count_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, count_);
      }
      for (int i = 0; i < params_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, params_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.panda.game.proto.CommonPb.DropItemMessagePb)) {
        return super.equals(obj);
      }
      com.panda.game.proto.CommonPb.DropItemMessagePb other = (com.panda.game.proto.CommonPb.DropItemMessagePb) obj;

      if (getItemId()
          != other.getItemId()) return false;
      if (getCount()
          != other.getCount()) return false;
      if (!getParamsList()
          .equals(other.getParamsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEMID_FIELD_NUMBER;
      hash = (53 * hash) + getItemId();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCount());
      if (getParamsCount() > 0) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParamsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.CommonPb.DropItemMessagePb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.panda.game.proto.CommonPb.DropItemMessagePb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 掉落道具信息
     * </pre>
     *
     * Protobuf type {@code com.panda.game.proto.DropItemMessagePb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.panda.game.proto.DropItemMessagePb)
        com.panda.game.proto.CommonPb.DropItemMessagePbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_DropItemMessagePb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_DropItemMessagePb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.panda.game.proto.CommonPb.DropItemMessagePb.class, com.panda.game.proto.CommonPb.DropItemMessagePb.Builder.class);
      }

      // Construct using com.panda.game.proto.CommonPb.DropItemMessagePb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getParamsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        itemId_ = 0;

        count_ = 0L;

        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          paramsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.panda.game.proto.CommonPb.internal_static_com_panda_game_proto_DropItemMessagePb_descriptor;
      }

      @java.lang.Override
      public com.panda.game.proto.CommonPb.DropItemMessagePb getDefaultInstanceForType() {
        return com.panda.game.proto.CommonPb.DropItemMessagePb.getDefaultInstance();
      }

      @java.lang.Override
      public com.panda.game.proto.CommonPb.DropItemMessagePb build() {
        com.panda.game.proto.CommonPb.DropItemMessagePb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.panda.game.proto.CommonPb.DropItemMessagePb buildPartial() {
        com.panda.game.proto.CommonPb.DropItemMessagePb result = new com.panda.game.proto.CommonPb.DropItemMessagePb(this);
        int from_bitField0_ = bitField0_;
        result.itemId_ = itemId_;
        result.count_ = count_;
        if (paramsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            params_ = java.util.Collections.unmodifiableList(params_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.panda.game.proto.CommonPb.DropItemMessagePb) {
          return mergeFrom((com.panda.game.proto.CommonPb.DropItemMessagePb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.panda.game.proto.CommonPb.DropItemMessagePb other) {
        if (other == com.panda.game.proto.CommonPb.DropItemMessagePb.getDefaultInstance()) return this;
        if (other.getItemId() != 0) {
          setItemId(other.getItemId());
        }
        if (other.getCount() != 0L) {
          setCount(other.getCount());
        }
        if (paramsBuilder_ == null) {
          if (!other.params_.isEmpty()) {
            if (params_.isEmpty()) {
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureParamsIsMutable();
              params_.addAll(other.params_);
            }
            onChanged();
          }
        } else {
          if (!other.params_.isEmpty()) {
            if (paramsBuilder_.isEmpty()) {
              paramsBuilder_.dispose();
              paramsBuilder_ = null;
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000001);
              paramsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getParamsFieldBuilder() : null;
            } else {
              paramsBuilder_.addAllMessages(other.params_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.panda.game.proto.CommonPb.DropItemMessagePb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.panda.game.proto.CommonPb.DropItemMessagePb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int itemId_ ;
      /**
       * <pre>
       * item表id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       * @return The itemId.
       */
      @java.lang.Override
      public int getItemId() {
        return itemId_;
      }
      /**
       * <pre>
       * item表id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       * @param value The itemId to set.
       * @return This builder for chaining.
       */
      public Builder setItemId(int value) {
        
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * item表id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemId() {
        
        itemId_ = 0;
        onChanged();
        return this;
      }

      private long count_ ;
      /**
       * <pre>
       * 数量
       * </pre>
       *
       * <code>int64 count = 2;</code>
       * @return The count.
       */
      @java.lang.Override
      public long getCount() {
        return count_;
      }
      /**
       * <pre>
       * 数量
       * </pre>
       *
       * <code>int64 count = 2;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(long value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数量
       * </pre>
       *
       * <code>int64 count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.panda.game.proto.CommonPb.ParamPb> params_ =
        java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          params_ = new java.util.ArrayList<com.panda.game.proto.CommonPb.ParamPb>(params_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.panda.game.proto.CommonPb.ParamPb, com.panda.game.proto.CommonPb.ParamPb.Builder, com.panda.game.proto.CommonPb.ParamPbOrBuilder> paramsBuilder_;

      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public java.util.List<com.panda.game.proto.CommonPb.ParamPb> getParamsList() {
        if (paramsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(params_);
        } else {
          return paramsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public int getParamsCount() {
        if (paramsBuilder_ == null) {
          return params_.size();
        } else {
          return paramsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public com.panda.game.proto.CommonPb.ParamPb getParams(int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);
        } else {
          return paramsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public Builder setParams(
          int index, com.panda.game.proto.CommonPb.ParamPb value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.set(index, value);
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public Builder setParams(
          int index, com.panda.game.proto.CommonPb.ParamPb.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.set(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public Builder addParams(com.panda.game.proto.CommonPb.ParamPb value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public Builder addParams(
          int index, com.panda.game.proto.CommonPb.ParamPb value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(index, value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public Builder addParams(
          com.panda.game.proto.CommonPb.ParamPb.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public Builder addParams(
          int index, com.panda.game.proto.CommonPb.ParamPb.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends com.panda.game.proto.CommonPb.ParamPb> values) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, params_);
          onChanged();
        } else {
          paramsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          paramsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public Builder removeParams(int index) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.remove(index);
          onChanged();
        } else {
          paramsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public com.panda.game.proto.CommonPb.ParamPb.Builder getParamsBuilder(
          int index) {
        return getParamsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public com.panda.game.proto.CommonPb.ParamPbOrBuilder getParamsOrBuilder(
          int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);  } else {
          return paramsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public java.util.List<? extends com.panda.game.proto.CommonPb.ParamPbOrBuilder> 
           getParamsOrBuilderList() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(params_);
        }
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public com.panda.game.proto.CommonPb.ParamPb.Builder addParamsBuilder() {
        return getParamsFieldBuilder().addBuilder(
            com.panda.game.proto.CommonPb.ParamPb.getDefaultInstance());
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public com.panda.game.proto.CommonPb.ParamPb.Builder addParamsBuilder(
          int index) {
        return getParamsFieldBuilder().addBuilder(
            index, com.panda.game.proto.CommonPb.ParamPb.getDefaultInstance());
      }
      /**
       * <pre>
       * 其他参数
       * </pre>
       *
       * <code>repeated .com.panda.game.proto.ParamPb params = 3;</code>
       */
      public java.util.List<com.panda.game.proto.CommonPb.ParamPb.Builder> 
           getParamsBuilderList() {
        return getParamsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.panda.game.proto.CommonPb.ParamPb, com.panda.game.proto.CommonPb.ParamPb.Builder, com.panda.game.proto.CommonPb.ParamPbOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.panda.game.proto.CommonPb.ParamPb, com.panda.game.proto.CommonPb.ParamPb.Builder, com.panda.game.proto.CommonPb.ParamPbOrBuilder>(
                  params_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.panda.game.proto.DropItemMessagePb)
    }

    // @@protoc_insertion_point(class_scope:com.panda.game.proto.DropItemMessagePb)
    private static final com.panda.game.proto.CommonPb.DropItemMessagePb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.panda.game.proto.CommonPb.DropItemMessagePb();
    }

    public static com.panda.game.proto.CommonPb.DropItemMessagePb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DropItemMessagePb>
        PARSER = new com.google.protobuf.AbstractParser<DropItemMessagePb>() {
      @java.lang.Override
      public DropItemMessagePb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DropItemMessagePb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DropItemMessagePb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DropItemMessagePb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.panda.game.proto.CommonPb.DropItemMessagePb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_panda_game_proto_ParamPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_panda_game_proto_ParamPb_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_panda_game_proto_DropMessagePb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_panda_game_proto_DropMessagePb_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_panda_game_proto_DropItemMessagePb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_panda_game_proto_DropItemMessagePb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\024com.panda.game.proto\"&\n\007" +
      "ParamPb\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"F\n\r" +
      "DropMessagePb\0225\n\004list\030\001 \003(\0132\'.com.panda." +
      "game.proto.DropItemMessagePb\"a\n\021DropItem" +
      "MessagePb\022\016\n\006itemId\030\001 \001(\005\022\r\n\005count\030\002 \001(\003" +
      "\022-\n\006params\030\003 \003(\0132\035.com.panda.game.proto." +
      "ParamPbB \n\024com.panda.game.protoB\010CommonP" +
      "bb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_panda_game_proto_ParamPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_panda_game_proto_ParamPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_panda_game_proto_ParamPb_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_com_panda_game_proto_DropMessagePb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_panda_game_proto_DropMessagePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_panda_game_proto_DropMessagePb_descriptor,
        new java.lang.String[] { "List", });
    internal_static_com_panda_game_proto_DropItemMessagePb_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_panda_game_proto_DropItemMessagePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_panda_game_proto_DropItemMessagePb_descriptor,
        new java.lang.String[] { "ItemId", "Count", "Params", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
