// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: redis.proto

package com.panda.game.proto;

public final class RedisPb {
  private RedisPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * redis订阅cmd
   * </pre>
   *
   * Protobuf enum {@code com.panda.game.proto.RedisCmd}
   */
  public enum RedisCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 玩家在线消息
     * </pre>
     *
     * <code>Player_Online_Message = 0;</code>
     */
    Player_Online_Message(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 玩家在线消息
     * </pre>
     *
     * <code>Player_Online_Message = 0;</code>
     */
    public static final int Player_Online_Message_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RedisCmd valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RedisCmd forNumber(int value) {
      switch (value) {
        case 0: return Player_Online_Message;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RedisCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RedisCmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RedisCmd>() {
            public RedisCmd findValueByNumber(int number) {
              return RedisCmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.panda.game.proto.RedisPb.getDescriptor().getEnumTypes().get(0);
    }

    private static final RedisCmd[] VALUES = values();

    public static RedisCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RedisCmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.panda.game.proto.RedisCmd)
  }

  public interface PlayerOnlinePbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.panda.game.proto.PlayerOnlinePb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 经验
     * </pre>
     *
     * <code>int32 lv = 1;</code>
     * @return The lv.
     */
    int getLv();

    /**
     * <pre>
     * 经验
     * </pre>
     *
     * <code>int32 exp = 2;</code>
     * @return The exp.
     */
    int getExp();

    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>string pic = 4;</code>
     * @return The pic.
     */
    java.lang.String getPic();
    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>string pic = 4;</code>
     * @return The bytes for pic.
     */
    com.google.protobuf.ByteString
        getPicBytes();
  }
  /**
   * <pre>
   * 在线玩家数据
   * </pre>
   *
   * Protobuf type {@code com.panda.game.proto.PlayerOnlinePb}
   */
  public static final class PlayerOnlinePb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.panda.game.proto.PlayerOnlinePb)
      PlayerOnlinePbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerOnlinePb.newBuilder() to construct.
    private PlayerOnlinePb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerOnlinePb() {
      name_ = "";
      pic_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerOnlinePb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerOnlinePb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              lv_ = input.readInt32();
              break;
            }
            case 16: {

              exp_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              pic_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.panda.game.proto.RedisPb.internal_static_com_panda_game_proto_PlayerOnlinePb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.panda.game.proto.RedisPb.internal_static_com_panda_game_proto_PlayerOnlinePb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.panda.game.proto.RedisPb.PlayerOnlinePb.class, com.panda.game.proto.RedisPb.PlayerOnlinePb.Builder.class);
    }

    public static final int LV_FIELD_NUMBER = 1;
    private int lv_;
    /**
     * <pre>
     * 经验
     * </pre>
     *
     * <code>int32 lv = 1;</code>
     * @return The lv.
     */
    @java.lang.Override
    public int getLv() {
      return lv_;
    }

    public static final int EXP_FIELD_NUMBER = 2;
    private int exp_;
    /**
     * <pre>
     * 经验
     * </pre>
     *
     * <code>int32 exp = 2;</code>
     * @return The exp.
     */
    @java.lang.Override
    public int getExp() {
      return exp_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PIC_FIELD_NUMBER = 4;
    private volatile java.lang.Object pic_;
    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>string pic = 4;</code>
     * @return The pic.
     */
    @java.lang.Override
    public java.lang.String getPic() {
      java.lang.Object ref = pic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pic_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>string pic = 4;</code>
     * @return The bytes for pic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPicBytes() {
      java.lang.Object ref = pic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lv_ != 0) {
        output.writeInt32(1, lv_);
      }
      if (exp_ != 0) {
        output.writeInt32(2, exp_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getPicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, pic_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (lv_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, lv_);
      }
      if (exp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, exp_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getPicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, pic_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.panda.game.proto.RedisPb.PlayerOnlinePb)) {
        return super.equals(obj);
      }
      com.panda.game.proto.RedisPb.PlayerOnlinePb other = (com.panda.game.proto.RedisPb.PlayerOnlinePb) obj;

      if (getLv()
          != other.getLv()) return false;
      if (getExp()
          != other.getExp()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getPic()
          .equals(other.getPic())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LV_FIELD_NUMBER;
      hash = (53 * hash) + getLv();
      hash = (37 * hash) + EXP_FIELD_NUMBER;
      hash = (53 * hash) + getExp();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PIC_FIELD_NUMBER;
      hash = (53 * hash) + getPic().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panda.game.proto.RedisPb.PlayerOnlinePb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.panda.game.proto.RedisPb.PlayerOnlinePb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 在线玩家数据
     * </pre>
     *
     * Protobuf type {@code com.panda.game.proto.PlayerOnlinePb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.panda.game.proto.PlayerOnlinePb)
        com.panda.game.proto.RedisPb.PlayerOnlinePbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.panda.game.proto.RedisPb.internal_static_com_panda_game_proto_PlayerOnlinePb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.panda.game.proto.RedisPb.internal_static_com_panda_game_proto_PlayerOnlinePb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.panda.game.proto.RedisPb.PlayerOnlinePb.class, com.panda.game.proto.RedisPb.PlayerOnlinePb.Builder.class);
      }

      // Construct using com.panda.game.proto.RedisPb.PlayerOnlinePb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        lv_ = 0;

        exp_ = 0;

        name_ = "";

        pic_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.panda.game.proto.RedisPb.internal_static_com_panda_game_proto_PlayerOnlinePb_descriptor;
      }

      @java.lang.Override
      public com.panda.game.proto.RedisPb.PlayerOnlinePb getDefaultInstanceForType() {
        return com.panda.game.proto.RedisPb.PlayerOnlinePb.getDefaultInstance();
      }

      @java.lang.Override
      public com.panda.game.proto.RedisPb.PlayerOnlinePb build() {
        com.panda.game.proto.RedisPb.PlayerOnlinePb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.panda.game.proto.RedisPb.PlayerOnlinePb buildPartial() {
        com.panda.game.proto.RedisPb.PlayerOnlinePb result = new com.panda.game.proto.RedisPb.PlayerOnlinePb(this);
        result.lv_ = lv_;
        result.exp_ = exp_;
        result.name_ = name_;
        result.pic_ = pic_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.panda.game.proto.RedisPb.PlayerOnlinePb) {
          return mergeFrom((com.panda.game.proto.RedisPb.PlayerOnlinePb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.panda.game.proto.RedisPb.PlayerOnlinePb other) {
        if (other == com.panda.game.proto.RedisPb.PlayerOnlinePb.getDefaultInstance()) return this;
        if (other.getLv() != 0) {
          setLv(other.getLv());
        }
        if (other.getExp() != 0) {
          setExp(other.getExp());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getPic().isEmpty()) {
          pic_ = other.pic_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.panda.game.proto.RedisPb.PlayerOnlinePb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.panda.game.proto.RedisPb.PlayerOnlinePb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int lv_ ;
      /**
       * <pre>
       * 经验
       * </pre>
       *
       * <code>int32 lv = 1;</code>
       * @return The lv.
       */
      @java.lang.Override
      public int getLv() {
        return lv_;
      }
      /**
       * <pre>
       * 经验
       * </pre>
       *
       * <code>int32 lv = 1;</code>
       * @param value The lv to set.
       * @return This builder for chaining.
       */
      public Builder setLv(int value) {
        
        lv_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 经验
       * </pre>
       *
       * <code>int32 lv = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLv() {
        
        lv_ = 0;
        onChanged();
        return this;
      }

      private int exp_ ;
      /**
       * <pre>
       * 经验
       * </pre>
       *
       * <code>int32 exp = 2;</code>
       * @return The exp.
       */
      @java.lang.Override
      public int getExp() {
        return exp_;
      }
      /**
       * <pre>
       * 经验
       * </pre>
       *
       * <code>int32 exp = 2;</code>
       * @param value The exp to set.
       * @return This builder for chaining.
       */
      public Builder setExp(int value) {
        
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 经验
       * </pre>
       *
       * <code>int32 exp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExp() {
        
        exp_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pic_ = "";
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>string pic = 4;</code>
       * @return The pic.
       */
      public java.lang.String getPic() {
        java.lang.Object ref = pic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>string pic = 4;</code>
       * @return The bytes for pic.
       */
      public com.google.protobuf.ByteString
          getPicBytes() {
        java.lang.Object ref = pic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>string pic = 4;</code>
       * @param value The pic to set.
       * @return This builder for chaining.
       */
      public Builder setPic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>string pic = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPic() {
        
        pic_ = getDefaultInstance().getPic();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>string pic = 4;</code>
       * @param value The bytes for pic to set.
       * @return This builder for chaining.
       */
      public Builder setPicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pic_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.panda.game.proto.PlayerOnlinePb)
    }

    // @@protoc_insertion_point(class_scope:com.panda.game.proto.PlayerOnlinePb)
    private static final com.panda.game.proto.RedisPb.PlayerOnlinePb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.panda.game.proto.RedisPb.PlayerOnlinePb();
    }

    public static com.panda.game.proto.RedisPb.PlayerOnlinePb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerOnlinePb>
        PARSER = new com.google.protobuf.AbstractParser<PlayerOnlinePb>() {
      @java.lang.Override
      public PlayerOnlinePb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerOnlinePb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerOnlinePb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerOnlinePb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.panda.game.proto.RedisPb.PlayerOnlinePb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_panda_game_proto_PlayerOnlinePb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_panda_game_proto_PlayerOnlinePb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013redis.proto\022\024com.panda.game.proto\"D\n\016P" +
      "layerOnlinePb\022\n\n\002lv\030\001 \001(\005\022\013\n\003exp\030\002 \001(\005\022\014" +
      "\n\004name\030\003 \001(\t\022\013\n\003pic\030\004 \001(\t*%\n\010RedisCmd\022\031\n" +
      "\025Player_Online_Message\020\000B\037\n\024com.panda.ga" +
      "me.protoB\007RedisPbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_panda_game_proto_PlayerOnlinePb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_panda_game_proto_PlayerOnlinePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_panda_game_proto_PlayerOnlinePb_descriptor,
        new java.lang.String[] { "Lv", "Exp", "Name", "Pic", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
